### ISSUE TITLE
A space is added to db file name

### ISSUE THREAD

**Issue by tannn** [tannn/TriviaTime#318]
Somehow or other, trivia.db turns into tri via.db

**Comment by brrr2** [comment]
The config name `TriviaTime.admin.sqlitedb` and config value `plugins/TriviaTime/storage/db/trivia.db` are too long when combined together and is broken into two lines when saved to a Supybot .conf file. It just so happens that the line break happens between 'tri' and 'via'. When this is read back from the .conf file the value for `TriviaTime.admin.sqlitedb` changes to  `plugins/TriviaTime/storage/db/tri via.db`. The same thing happens for the config value `plugins/TriviaTime/storage/samplequestions`.

This can be fixed by shortening the config name and/or value.
